/**
 * Artisan-style generator CLI (Laravel DX for this stack).
 *
 * Usage:
 *   bun scripts/make.ts <generator> <name>
 *   bun run make:model User
 *   bun run make:migration add_index_to_posts
 *
 * Generators:
 *   make:model       <PascalCaseName>   → Prisma model stub + feature service module
 *   make:migration   <snake_case_name>  → wraps `bunx prisma migrate dev --create-only`
 *
 * Deferred generators (see context/specs/02-laravel-dx-cli.md):
 *   make:controller, make:component, make:action, make:seeder, make:hook, make:schema
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

// ---------------------------------------------------------------------------
// Colored output helpers (ANSI)
// ---------------------------------------------------------------------------

type ColorCode = 32 | 33 | 36 | 31;

function colorize(text: string, code: ColorCode): string {
  return `\x1b[${code}m${text}\x1b[0m`;
}

const info = (msg: string): void => console.log(colorize(msg, 36)); // cyan
const success = (msg: string): void => console.log(colorize(msg, 32)); // green
const warn = (msg: string): void => console.log(colorize(msg, 33)); // yellow
const fail = (msg: string): void => console.error(colorize(msg, 31)); // red

function die(msg: string, hint?: string): never {
  fail(`ERROR: ${msg}`);
  if (hint) console.error(hint);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

/** "UserProfile" → "user-profile" */
function toKebabCase(input: string): string {
  return input
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/** "user-profile" → "userProfile" */
function toCamelCase(kebab: string): string {
  return kebab.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/** Naive English pluralization for table names / migration suffixes. */
function pluralize(word: string): string {
  if (/s$|x$|z$|ch$|sh$/.test(word)) return `${word}es`;
  if (/[^aeiou]y$/.test(word)) return `${word.slice(0, -1)}ies`;
  return `${word}s`;
}

interface NameValidationError {
  valid: boolean;
}

function validateModelName(name: string): NameValidationError & { reason?: string } {
  if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) {
    return {
      valid: false,
      reason: `Model names must be PascalCase (e.g. "BlogPost"), got "${name}".`,
    };
  }
  return { valid: true };
}

function validateMigrationName(name: string): NameValidationError & { reason?: string } {
  if (!/^[a-z][a-z0-9_]*$/.test(name)) {
    return {
      valid: false,
      reason: `Migration names must be snake_case (e.g. "add_soft_delete_to_post"), got "${name}".`,
    };
  }
  return { valid: true };
}

// ---------------------------------------------------------------------------
// Templates (pure string builders)
// ---------------------------------------------------------------------------

interface ModelTemplateContext {
  pascal: string;
  snakeTable: string;
}

/** Builds the Prisma model stub appended to prisma/schema.prisma. */
function buildPrismaModelStub(ctx: ModelTemplateContext): string {
  const { pascal, snakeTable } = ctx;
  return `
model ${pascal} {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("${snakeTable}")
}
`;
}

interface ServiceTemplateContext {
  pascal: string;
  kebab: string;
  camel: string;
}

/** Builds the feature service module with CRUD wrappers over the singleton. */
function buildServiceModule(ctx: ServiceTemplateContext): string {
  const { pascal, kebab, camel } = ctx;
  return `import prisma from "@/lib/prisma";

/**
 * CRUD service for the ${pascal} model.
 *
 * Generated by \`bun run make:model ${pascal}\`. Extend with domain-specific
 * queries as needed. All database calls follow the try-catch pattern from
 * context/code-standards.md.
 */

export interface FindMany${pascal}Options {
  skip?: number;
  take?: number;
}

export const ${camel}Service = {
  async findMany(options: FindMany${pascal}Options = {}) {
    try {
      return await prisma.${camel}.findMany({
        skip: options.skip,
        take: options.take,
        orderBy: { createdAt: "desc" },
      });
    } catch (error) {
      console.error("[${kebab}-service] findMany failed:", error);
      throw new Error("Failed to fetch ${camel} records.");
    }
  },

  async findById(id: string) {
    try {
      return await prisma.${camel}.findUnique({ where: { id } });
    } catch (error) {
      console.error("[${kebab}-service] findById failed:", error);
      throw new Error("Failed to fetch ${camel} record.");
    }
  },

  async create(data: Parameters<typeof prisma.${camel}.create>[0]["data"]) {
    try {
      return await prisma.${camel}.create({ data });
    } catch (error) {
      console.error("[${kebab}-service] create failed:", error);
      throw new Error("Failed to create ${camel} record.");
    }
  },

  async update(id: string, data: Parameters<typeof prisma.${camel}.update>[0]["data"]) {
    try {
      return await prisma.${camel}.update({ where: { id }, data });
    } catch (error) {
      console.error("[${kebab}-service] update failed:", error);
      throw new Error("Failed to update ${camel} record.");
    }
  },

  async delete(id: string) {
    try {
      return await prisma.${camel}.delete({ where: { id } });
    } catch (error) {
      console.error("[${kebab}-service] delete failed:", error);
      throw new Error("Failed to delete ${camel} record.");
    }
  },
};
`;
}

// ---------------------------------------------------------------------------
// Schema manipulation
// ---------------------------------------------------------------------------

const SCHEMA_PATH = path.resolve(process.cwd(), "prisma", "schema.prisma");

/** Returns true when a `model <name>` declaration already exists. */
function schemaHasModel(pascal: string): boolean {
  if (!existsSync(SCHEMA_PATH)) die("prisma/schema.prisma not found.");
  const schema = readFileSync(SCHEMA_PATH, "utf8");
  return new RegExp(`^model ${pascal}\\b`, "m").test(schema);
}

/**
 * Inserts the stub after the LAST existing model block (i.e. after all
 * models, but before anything declared after them such as trailing enums).
 */
function appendModelToSchema(stub: string): void {
  const schema = readFileSync(SCHEMA_PATH, "utf8");
  const modelBlockRe = /^model\s+\w+[\s\S]*?\n}/gm;
  let lastEnd = -1;
  let match: RegExpExecArray | null;
  while ((match = modelBlockRe.exec(schema)) !== null) {
    lastEnd = match.index + match[0].length;
  }
  if (lastEnd === -1) {
    // No existing models — append at end of file.
    writeFileSync(SCHEMA_PATH, schema.trimEnd() + "\n" + stub);
  } else {
    const next = schema.slice(lastEnd);
    const updated = schema.slice(0, lastEnd) + "\n" + stub + next;
    writeFileSync(SCHEMA_PATH, updated);
  }
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

interface GeneratorResult {
  ranMigration: boolean;
}

function generateModel(rawName: string, flags: string[]): GeneratorResult {
  const check = validateModelName(rawName);
  if (!check.valid) {
    die(check.reason ?? "Invalid model name.", 'Usage: bun run make:model <PascalCaseName>');
  }
  const pascal = rawName;
  if (schemaHasModel(pascal)) {
    die(
      `Model "${pascal}" already exists in prisma/schema.prisma.`,
      "Refusing to duplicate. Pick another name or edit the existing model."
    );
  }

  const kebab = toKebabCase(pascal);
  const snakeTable = kebab.replace(/-/g, "_");
  const serviceDir = path.resolve(process.cwd(), "features", kebab, "lib");
  const servicePath = path.join(serviceDir, `${kebab}.service.ts`);

  info(`Creating Prisma model ${pascal} (@@map("${snakeTable}"))...`);
  appendModelToSchema(buildPrismaModelStub({ pascal, snakeTable }));
  success(`  ✔ updated prisma/schema.prisma`);

  if (existsSync(servicePath)) {
    warn(`  ⚠ features/${kebab}/lib/${kebab}.service.ts already exists — skipped.`);
  } else {
    mkdirSync(serviceDir, { recursive: true });
    writeFileSync(
      servicePath,
      buildServiceModule({ pascal, kebab, camel: toCamelCase(kebab) })
    );
    success(`  ✔ created features/${kebab}/lib/${kebab}.service.ts`);
  }

  const wantsMigration = flags.includes("--migration") || flags.includes("-m");
  if (wantsMigration) {
    runPrismaMigration(`create_${pluralize(snakeTable)}_table`);
  } else {
    info("");
    info("Next steps:");
    info(`  bunx prisma migrate dev --name create_${pluralize(snakeTable)}_table`);
    info(`  bunx prisma generate`);
  }

  return { ranMigration: wantsMigration };
}

function runPrismaMigration(name: string): void {
  info(`Running: bunx prisma migrate dev --create-only --name ${name}`);
  const result = spawnSync("bunx", ["prisma", "migrate", "dev", "--create-only", "--name", name], {
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    die(`prisma migrate exited with code ${result.status ?? "unknown"}.`);
  }
  success(`  ✔ migration "${name}" created.`);
  info("Review the SQL, then apply with: bunx prisma migrate dev");
}

function generateMigration(rawName: string): GeneratorResult {
  const check = validateMigrationName(rawName);
  if (!check.valid) {
    die(
      check.reason ?? "Invalid migration name.",
      "Usage: bun run make:migration <snake_case_name>"
    );
  }
  warn("NOTE: Edit prisma/schema.prisma FIRST — it is the single source of truth.");
  warn("This creates an empty migration file you can adjust before applying.");
  runPrismaMigration(rawName);
  return { ranMigration: true };
}

// ---------------------------------------------------------------------------
// Registry + CLI dispatch
// ---------------------------------------------------------------------------

type GeneratorFn = (name: string, flags: string[]) => GeneratorResult;

interface GeneratorEntry {
  description: string;
  usage: string;
  run: GeneratorFn;
  deferred?: boolean;
}

const GENERATORS: Record<string, GeneratorEntry> = {
  "make:model": {
    description: "Prisma model stub + feature service module (features/<kebab>/lib/)",
    usage: "make:model <PascalCaseName> [--migration|-m]",
    run: generateModel,
  },
  "make:migration": {
    description: "Create-only Prisma migration (edit schema first)",
    usage: "make:migration <snake_case_name>",
    run: (name) => generateMigration(name),
  },
};

const DEFERRED: string[] = [
  "make:controller",
  "make:component",
  "make:action",
  "make:seeder",
  "make:hook",
  "make:schema",
];

function printHelp(): void {
  console.log("\nArtisan-style generators\n");
  console.log("Usage: bun scripts/make.ts <generator> <name>\n");
  console.log("Available:");
  for (const [key, entry] of Object.entries(GENERATORS)) {
    console.log(`  ${key.padEnd(16)} ${entry.description}`);
    console.log(`${"".padEnd(18)}usage: ${entry.usage}`);
  }
  if (DEFERRED.length > 0) {
    console.log(`\nDeferred (not implemented): ${DEFERRED.join(", ")}`);
  }
  console.log();
}

function main(argv: string[]): void {
  const [generator, ...rest] = argv;

  if (!generator || generator === "--help" || generator === "-h" || generator === "help") {
    printHelp();
    process.exit(generator ? 0 : 1);
  }

  const entry = GENERATORS[generator];
  if (!entry) {
    if (DEFERRED.includes(generator)) {
      die(`Generator "${generator}" is planned but not implemented yet.`, undefined);
    }
    die(`Unknown generator "${generator}".`, `Available: ${Object.keys(GENERATORS).join(", ")}`);
  }

  const name = rest.find((arg) => !arg.startsWith("-"));
  const flags = rest.filter((arg) => arg.startsWith("-"));
  if (!name) {
    die(`Missing name argument.`, `Usage: bun run ${entry.usage}`);
  }

  entry.run(name, flags);
  success("\nDone.");
}

main(process.argv.slice(2));
