import { renderPostContent } from "../lib/render";
import { cn } from "@/lib/utils";

interface EditorContentProps {
  content: string;
  className?: string;
}

/**
 * Read-only server-rendered preview of stored TipTap JSON.
 * Safe to use in Server Components — rendering happens on the server
 * via @tiptap/html and only HTML is shipped to the client.
 */
export function PostContent({ content, className }: EditorContentProps) {
  const html = renderPostContent(content);

  return (
    <div
      className={cn("prose-post", className)}
      // Content is generated by TipTap from editor-validated JSON; links are
      // emitted with rel/target set in extensions.ts.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
